blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('blog1.urls')),
    path('admin/', admin.site.urls),
]

blog1/urls.py
from django.urls import path
from blog1 import views
app_name = 'blog1'
urlpatterns = [
            path('',views.landing,name= 'landing'),
            path('loggedin/',views.next1,name= 'after'),
            path('signup/',views.registration,name='signup'),
            path('congo/',views.congo,name='congo'),
            path('login/',views.userlogin,name='login'),
            path('blogs/',views.postmaker,name='blogs'),
            path('logout/',views.userlogout,name='logout'),
            path('newpost/',views.newposter,name='poster'),
            path('drafts/<int:pk>/',views.draftsuser,name='drafts'),
            path('save/',views.publish,name='publish')


]

blog1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# class BlogContent(models.Model):
#         user = models.OneToOneField(User,on_delete=models.CASCADE)
#         Title = models.CharField(max_length = 20)
#         content = models.CharField(max_length=5000)
#         def __str__():
#             return self.user.username
#


class BlogContent11(models.Model):
        id = models.BigIntegerField(primary_key = True)
        user  = models.ForeignKey(User,related_name='stories',on_delete=models.CASCADE)
        title = models.CharField(max_length = 50)
        story = models.CharField(max_length=5000)
        def __str__(self):
            return self.user.username


class PublishUser(models.Model):
    title = models.CharField(max_length = 50)
    story = models.CharField(max_length=5000)
    author = models.CharField(max_length=100)
    def __str__(self):
        return self.title

blog1/forms.py
from django import forms
from django.forms import ModelForm
from blog1.models import *
from django.contrib.auth.models import User

# class BlogForm(forms.ModelForm):
#     class Meta():
#         model = 'BlogContent'
#         fields = ('Title','content')


class authenticateform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields =('username','email','password')

class BlogContent1Form(forms.ModelForm):
    class Meta():
        model = BlogContent11
        fields = ('title','story')

blog1/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from blog1.forms import *
from blog1.models import *
from django.contrib.auth.models import User
# Create your views here.
def landing(request):
    objects = PublishUser.objects.order_by('-id')

    context ={'lists':objects}
    return render(request,'blog1/landing.html',context)


def userlogin(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('blog1:blogs'))
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('pass')
            user = authenticate(username= username,password=password)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('blog1:blogs'))
                else:
                    return HttpResponse("Account not active")
            else:
                print("someone tried to login and failed ")
                print(f"Username :{username} and password :{password}")
                return HttpResponse("Invalid login credentials")

        else:
            return render(request,'blog1/login.html',context={})

# @login_required
def next1(request):
    return render(request,'blog1/after.html',context={})

@login_required
def userlogout(request):
    logout(request)
    return render(request,'blog1/landing.html')
#
def registration(request):
    registered = False
    if request.method == "POST":


        user_form = authenticateform(request.POST)

        if user_form.is_valid():
            username = user_form.cleaned_data.get('username')
            password = user_form.cleaned_data.get('password')
            email = user_form.cleaned_data.get('email')
            print(username,password)
            user_obj = User(username=username,password= password,email=email)
            print('hello1')

            user_obj.set_password(user_obj.password)
            print('hello2')
            user_obj.save()
            print('hello3')
            registered = True
            print('hello4')
            return HttpResponseRedirect(reverse('blog1:congo'))
        else:
            print(user_form.errors)
    else:

        context={"registered":registered}
        return render(request,'blog1/signup1.html',context)


## this works too
# def registration(request):
#     registered = False
#     if request.method == "POST":
#
#
#         user_form = authenticateform(request.POST)
#
#         if user_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#             registered = True
#         else:
#             print(user_form.errors)
#     else:
#         form =  authenticateform()
#         context={'registered':registered,'form':form}
#         return render(request,'blog1/signup1.html',context)
def congo(request):
    return render(request,'blog1/congrats.html',)


@login_required
def postmaker(request):
    x=[]
    objects = PublishUser.objects.all()
    type(objects)
    for obj in objects:
        if obj.author == request.user.username:
                print(obj)
                x.append(obj)
        else:
            continue
    context={'lists':x}
    print(x)

    return render(request,'blog1/blogs.html',context)


@login_required
def newposter(request):
    if request.method == "POST":
        form = BlogContent1Form(request.POST)
        print('hello1')
        if form.is_valid():
            print('hello2')

            # form.user=user
            # form.save()
            user1= request.user

            user = User.objects.get(id=user1.id)
            # user = request.user.userna
            title = form.cleaned_data['title']
            story = form.cleaned_data['story']


            print('hello3')

            form11 = BlogContent11(user=user,title=title,story=story)

            print('hello4')
            form11.save()
            print('hello5')
            return HttpResponseRedirect(reverse('blog1:blogs'))
        else:
            print(form.errors)
    return render(request,'blog1/newpost.html')




@login_required
def draftsuser(request,pk):

     model = User.objects.get(id=pk)
     print(model)
     context = {'objects':model}
     return render(request,'blog1/drafts.html',context)


def publish(request):
    print('hello')
    if request.method == "POST":

        print('hello')
        author = request.POST['user']
        title = request.POST['title']
        story = request.POST['story']
        model = PublishUser(author=author,title=title,story=story)
        model.save()
        return HttpResponseRedirect(reverse('blog1:blogs'))

blog1/templates/blog1/after.html
{% extends "blog1/base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron" id='after'>
    <h1 >Hi</h1>
    <h3>This is my first webisite!!</h3>
    <h3>In this people can write their own stories</h3>
    <h3>I hope you to write some weird stories</h3>

  </div>

</div>
{% endblock %}

blog1/templates/blog1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
    <meta charset="utf-8">
    <title>Blog</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='mav'>

        <a class="navbar-brand" id = 'hello' href="{% url 'blog1:landing' %}">Stories</a>
        <button class="navbar-toggler " id = 'hello11'  type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog1:after' %}">About<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/Rahulvvsv">Github</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" disabled href="#">LinkedIn</a>
            </li>

          </ul>
          {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"   >
              <a class="nav-link" href="{% url 'blog1:login' %}">{{user.username}}</a>
            </li>
          </ul>
          {% else%}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"   >
              <a class="nav-link" href="{% url 'blog1:login' %}">Login</a>
            </li>
          </ul>
          {% endif %}

        </div>



      </nav>

    {% block content %}
    {% endblock %}



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
</html>

blog1/templates/blog1/blogs.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/landing.css' %}">
      <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
    <title>Blogs</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='mav'>

        <a class="navbar-brand" id = 'hello' href="{% url 'blog1:landing' %}">Stories</a>
        <button class="navbar-toggler " id = 'hello11'  type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog1:after' %}">About<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/Rahulvvsv">Github</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">LinkedIn</a>
            </li>

          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated   %}
            <li class="nav-item active">
            <a class="nav-link" href="{% url "blog1:logout" %}">Logout<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
            <li class="nav-item"   >
                <a class="nav-link" href="{% url 'blog1:poster' %}">NEW POST</a>

            </li>
            <li class='nav-item'>
                  <a class="nav-link" href="{% url 'blog1:drafts' pk=user.id %}">DRAFTS</a>
            </li>
          </ul>
        </div>


      </nav>
      <div class="container">
        <div class="jumbotron" id='welcome'>
          <h1>Welcome {{user.username}}</h1>
                <h6>Make new stories in NewPost</h6>
                <h6>Your stories are stored in drafts</h6>
                <small>You can publilsh from there</small>


        </div>
        <hr>
        <div id='rahul'>
            <h1  >Your Posts:</h1>
        </div>

      </div>
      <div class="container">


            {% for item in lists %}
            <div class="container">
              <div class="jumbotron" id="what">
                <h1 class='hello' id='luhar' >{{item.title}}</h1>
                <textarea name="name" readonly rows="8" cols="80" class='form-control ' id='story'>

                  {{item.story}}

                </textarea>
                <div class="storyby">
                    <small >Story by:<p>{{item.author}}</p></small>

                </div>
                <small>This story is Published</small>


              </div>

            </div>
            {% endfor %}


          </div>






















      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>

blog1/templates/blog1/congrats.html
{% extends "blog1/base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Thank you for registering!!!</h1>
    <h3>You can now Login </h3>

  </div>

</div>
{% endblock %}

blog1/templates/blog1/drafts.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/landing.css' %}">
    <title>Blogs</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='mav'>

        <a class="navbar-brand" id = 'hello' href="{% url 'blog1:landing' %}">Stories</a>
        <button class="navbar-toggler " id = 'hello11'  type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog1:after' %}">About<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/Rahulvvsv">Github</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">LinkedIn</a>
            </li>
          </ul>


            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated   %}
              <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog1:logout' %}" >Logout<span class="sr-only">(current)</span></a>
              </li>
              {% endif %}
              <li class="nav-item"   >
                  <a class="nav-link" href="{% url 'blog1:poster' %}">NEW POST</a>

              </li>
              <li class='nav-item'>
                    <a class="nav-link" href="{% url 'blog1:drafts' pk=user.id %}">DRAFTS</a>
              </li>
            </ul>


        </div>

      </nav>
      <div class="container">
        <div class="jumbotron" id='posts'>
            <ol>
          {% for stud in objects.stories.all %}



              <li>
                <form method="post" action="{% url 'blog1:publish' %}">
                          {% csrf_token %}
                <div class="form-group row">
                  <label for="staticEmail" class="col-sm-2 col-form-label">Author</label>
                  <div class="col-sm-10">
                    <input type="text" name = "user" readonly class="form-control" id="staticEmail" value={{user.username}} >
                  </div>
                </div>
                <div class="form-group row">
                  <label for="staticEmail" class="col-sm-2 col-form-label">Title</label>
                  <div class="col-sm-10">
                      <input type="text"  readonly class="form-control" id="staticEmail" name='title' value={{stud.title}}>
                  </div>
                </div>
                <div class="form-group row">
                      <label for="inputPassword" class="col-sm-2 col-form-label">Text</label>
                    <div class="col-sm-10">
                    <textarea name="story" readonly rows="8" cols="80" class='form-control' id='story' >{{stud.story}}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-lg-4">
                      <input type="submit" name="" class='btn btn-primary'value="Publish">
                    </div>
                </div>
              </form>
            </li>

          <hr>
            {% endfor %}
          </ol>


          </div>

        </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


  </body>
</html>

blog1/templates/blog1/landing.html
{% extends "blog1/base.html" %}



    {% block content %}
    <div class="container " id='rahul'>
      <h1>Posts:</h1>
      
    </div>

    {% for item in lists %}
    <div class="container">
      <div class="jumbotron" id="what">
        <h1 class='hello' id='luhar' >{{item.title}}</h1>
        <textarea name="name" readonly rows="8" cols="80" class='form-control ' id='story'>

          {{item.story}}

        </textarea>
        <div class="storyby">
            <small >Story by:<p>{{item.author}}</p></small>
        </div>


      </div>

    </div>
    {% endfor %}

    {% endblock %}

blog1/templates/blog1/login.html
{% extends "blog1/base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron" id='when'>

    <h1>Please Login:</h1>
    <!-- <small>Must be a superuser </small> -->
    <hr>
    <!-- <form class=""  method="post">
      {% csrf_token %}
      <label for="username"><strong>Username:</strong></label>

      <input type="text" name="username" placeholder="Username">
      <p></p>
        <label for="pass"><strong>Password:</strong></label>
      <input type="password" name="pass" placeholder="password">
      <p></p>
      <input type="submit" name="" value="Login">
    </form> -->

        <form method='post'>
          {% csrf_token %}
      <div class="form-group row">
        <label for="staticEmail" class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
          <input type="text"  class="form-control"  name="username"  placeholder="Username">
        </div>
      </div>
      <div class="form-group row">
        <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" id="inputPassword" placeholder="Password" name="pass">
        </div>
      </div>
      <div class="form-group row" id='button'>
      <p align='right'><input type="submit" class= 'btn btn-primary '  name="" value="Login"></p>

    </div>

    </form>
    <p></p>
    <small>Don't have an account??  <a href="{% url 'blog1:signup' %}"> signup</a></small>


  </div>
</div>

{% endblock %}

blog1/templates/blog1/newpost.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/landing.css' %}">
    <title>Blogs</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='mav'>

        <a class="navbar-brand" id = 'hello' href="{% url 'blog1:landing' %}">Stories</a>
        <button class="navbar-toggler " id = 'hello11'  type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog1:after' %}">About<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/Rahulvvsv">Github</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">LinkedIn</a>
            </li>
          </ul>


            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated   %}
              <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog1:logout' %}" >Logout<span class="sr-only">(current)</span></a>
              </li>
              {% endif %}
              <li class="nav-item"   >
                  <a class="nav-link" href="{% url 'blog1:poster' %}">NEW POST</a>

              </li>
              <li class='nav-item'>
                    <a class="nav-link" href="{% url 'blog1:drafts' pk=user.id %}">DRAFTS</a>
              </li>
            </ul>


        </div>

      </nav>
      <div class="container">
        <div class="jumbotron" id='newpost'>
          <h1>NEW POST</h1>
          <hr>


          <form method="post" action="{% url 'blog1:poster'  %}">
            {% csrf_token %}
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Author</label>
                <div class="col-sm-10">
                  <input type="text" readonly class="form-control" id="staticEmail" value="{{user.username}} " name='user' >
                </div>
            </div>
            <div class="form-group row">
              <label for="staticEmail" class="col-sm-2 col-form-label">Title</label>
              <div class="col-sm-10">
                <input type="text"  class="form-control" id="staticEmail" name='title'>
              </div>
            </div>
            <div class="form-group row">
              <label for="inputPassword" class="col-sm-2 col-form-label">Text</label>
              <div class="col-sm-10">
                <!-- <input type="text" class="form-control" id="inputPassword" placeholder="Write Your Story Here!!"> -->
                <textarea name="story" rows="8" cols="80" class='form-control' placeholder="Write Your Story Here!!"></textarea>

              </div>
            </div>
            <div class="form-group row">
              <input type="submit"class='form-control btn btn-primary' name="" value="SUBMIT">

            </div>
          </form>
          <small>Your stories are stored in drafts </small>

        </div>

      </div>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


  </body>
</html>

blog1/templates/blog1/signup.html
{% extends "blog1/base.html" %}
{% block content %}
{% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}

  <div class="container">
    <div class="jumbotron">


      <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
              {{field.label}}
              {{field}}

            </div>

            <p></p>
            {% endfor %}
              <input type="submit" name="" value="register">
      </form>

    </div>

  </div>
  {% endif %}
{% endblock %}

blog1/templates/blog1/signup1.html
{% extends "blog1/base.html" %}
{% block content %}
  {% if registered %}
  <h1>Thank you for registering</h1>
  {% else %}

  <div class="container">
    <div class="jumbotron" id='where'>


      <form method='POST' >
            {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">Username</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name='username'>

        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"  name="email" >
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password" >
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

    </div>

  </div>
  {% endif %}
{% endblock %}